-- =====================================================================
-- OPTRACKER - baseline del esquema
-- Generado por introspeccion del proyecto Supabase el 2026-08-06.
--
-- Este archivo NO se ejecuta sobre la base actual: es la linea base que
-- documenta el estado del esquema en el momento en que se empezo a
-- versionar. Sirve para (a) revisar la seguridad en un pull request en
-- vez de en el dashboard, y (b) poder levantar un entorno de pruebas
-- desde cero.
--
-- A partir de aca, TODO cambio de esquema va como una migracion nueva
-- numerada en esta carpeta. Ver supabase/README.md.
--
-- VERIFICADO: este archivo se ejecuto completo contra un esquema
-- descartable el 2026-08-06 y reprodujo 15 tablas, 50 politicas y RLS
-- en las 15 tablas, identico a produccion.
--
-- El ORDEN de los bloques importa: es_admin() y puede_editar() son
-- funciones SQL (no plpgsql), asi que Postgres valida su cuerpo al
-- crearlas y necesitan que la tabla usuarios ya exista. Por eso van
-- despues de las tablas, no antes.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Funciones de apoyo (sin dependencias de tablas)
-- ---------------------------------------------------------------------

-- Genera codigos correlativos por modulo: OPT-001, TAR-001, RAD-001, VJ-001, CI-001
create or replace function public.set_codigo(pref text, tabla text)
returns text language plpgsql set search_path = 'public' as $$
declare n int;
begin
  execute format(
    'select coalesce(max(nullif(regexp_replace(codigo, ''\D'', '''', ''g''), '''')::int), 0) + 1 from %I where codigo like %L',
    tabla, pref || '-%'
  ) into n;
  return pref || '-' || lpad(n::text, 3, '0');
end $$;

create or replace function public.tocar_updated_at()
returns trigger language plpgsql set search_path = 'public' as $$
begin new.updated_at := now(); return new; end $$;

-- ---------------------------------------------------------------------
-- 2. Tablas
-- ---------------------------------------------------------------------

create table if not exists public.personas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  rol text,
  email text,
  horas_mes numeric default 168,
  activo boolean default true,
  orden integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id),
  email text not null,
  nombre text,
  rol text not null default 'lector' check (rol in ('admin','editor','lector')),
  persona_id bigint references public.personas(id),
  telefono text,
  activo boolean default true,
  created_at timestamptz default now(),
  debe_cambiar_password boolean default true,
  onboarding_visto boolean default false
);

create table if not exists public.actividades (
  id bigint generated by default as identity primary key,
  pilar text,
  categoria text,
  nombre text not null,
  prioridad text,
  orden integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.participaciones (
  id bigint generated by default as identity primary key,
  actividad_id bigint references public.actividades(id),
  persona_id bigint references public.personas(id),
  porcentaje numeric not null default 0,
  mes date not null
);

create table if not exists public.capacidad_mensual (
  id bigint generated by default as identity primary key,
  persona_id bigint references public.personas(id),
  mes date not null,
  horas_disponibles numeric not null default 168
);

create table if not exists public.portafolio (
  id bigint generated by default as identity primary key,
  codigo text unique,
  pais text,
  area_solicitante text,
  problema text,
  origen text,
  fase text,
  prioridad text,
  responsable text,
  fecha_inicio date,
  proximo_hito text,
  fecha_hito date,
  estado text,
  metrica_base text,
  metrica_objetivo text,
  metrica_actual text,
  motivo_descarte text,
  enlace text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.tareas (
  id bigint generated by default as identity primary key,
  codigo text unique,
  iniciativa_codigo text,
  tarea text not null,
  responsable text,
  fecha_limite date,
  estado text default 'Pendiente',
  notas text,
  enlace text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.radar_paises (
  id bigint generated by default as identity primary key,
  codigo text unique,
  pais text,
  indicador text,
  umbral numeric,
  valor_actual numeric,
  ultima_actualizacion date,
  notas text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.contactos_paises (
  id bigint generated by default as identity primary key,
  pais text,
  nombre text,
  rol text,
  contacto text,
  ultima_interaccion date,
  relacion text,
  notas text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.calendario_visitas (
  id bigint generated by default as identity primary key,
  codigo text unique,
  pais text,
  contacto text,
  trimestre text,
  fecha_programada date,
  fecha_fin date,
  responsable text,
  estado_visita text,
  etapa text default '1 · Propuesta',
  oportunidades text,
  iniciativa_codigo text,
  temas text,
  participantes text,
  notas text,
  decision text,
  motivo_descarte text,
  aviso_rrhh date,
  vuelos boolean default false,
  hotel boolean default false,
  agenda boolean default false,
  viaticos boolean default false,
  costo_estimado numeric,
  enlace text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Asistente Lean / Six Sigma. Los triggers y listas propios de este
-- modulo estan en 0002_mejora_continua.sql.
create table if not exists public.mejora_continua (
  id bigint generated by default as identity primary key,
  codigo text unique,
  titulo text not null,
  descripcion text not null,
  modulo_origen text,
  reportado_por uuid references public.usuarios(id),
  reportado_por_nombre text,
  fecha_reporte timestamptz not null default now(),
  severidad text not null default 'Medio',
  estado text not null default 'Definir',
  tipo_desperdicio text,
  sugerencia_desperdicio text,
  impacto_medido text,
  metodo_analisis text,
  causa_raiz text,
  accion_mejora text,
  accion_control text,
  responsable uuid references public.usuarios(id),
  fecha_objetivo date,
  fecha_cierre date,
  reincidente boolean not null default false,
  vinculado_a bigint references public.mejora_continua(id),
  enlace text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.historial (
  id bigint generated by default as identity primary key,
  tabla text not null,
  fila_id text,
  campo text,
  antes text,
  despues text,
  accion text not null,
  usuario_id uuid,
  usuario text,
  ts timestamptz default now()
);

-- Listas editables desde Configuracion (no hace falta tocar codigo para
-- agregar un pais, una fase, un estado, etc.)
create table if not exists public.config_listas (
  id bigint generated by default as identity primary key,
  tipo text not null,
  valor text not null,
  orden integer default 0,
  avance numeric,
  activo boolean default true,
  updated_at timestamptz default now()
);

create table if not exists public.ajustes (
  clave text primary key,
  valor text,
  etiqueta text,
  descripcion text,
  unidad text,
  orden integer default 0
);

-- Sin politicas RLS a proposito: nada del cliente debe poder leerla.
create table if not exists public.secretos (
  clave text primary key,
  valor text not null
);

-- ---------------------------------------------------------------------
-- 3. Control de acceso por rol
--    (van DESPUES de las tablas: dependen de public.usuarios)
-- ---------------------------------------------------------------------

create or replace function public.es_admin()
returns boolean language sql security definer set search_path = 'public' as $$
  select exists (select 1 from usuarios where id = auth.uid() and rol = 'admin' and activo);
$$;

create or replace function public.puede_editar()
returns boolean language sql security definer set search_path = 'public' as $$
  select exists (select 1 from usuarios where id = auth.uid() and rol in ('admin','editor') and activo);
$$;

-- ---------------------------------------------------------------------
-- 4. Funciones de trigger
-- ---------------------------------------------------------------------

create or replace function public.set_codigo_portafolio()
returns trigger language plpgsql set search_path = 'public' as $$
declare n int;
begin
  if new.codigo is null or new.codigo = '' then
    select coalesce(max((regexp_replace(codigo,'\D','','g'))::int),0)+1 into n
      from portafolio where codigo like 'OPT-%';
    new.codigo := 'OPT-' || lpad(n::text,3,'0');
  end if;
  return new;
end $$;

create or replace function public.codigo_tarea()
returns trigger language plpgsql set search_path = 'public' as $$
begin if new.codigo is null or new.codigo = '' then new.codigo := set_codigo('TAR','tareas'); end if; return new; end $$;

create or replace function public.codigo_radar()
returns trigger language plpgsql set search_path = 'public' as $$
begin if new.codigo is null or new.codigo = '' then new.codigo := set_codigo('RAD','radar_paises'); end if; return new; end $$;

create or replace function public.codigo_viaje()
returns trigger language plpgsql set search_path = 'public' as $$
begin if new.codigo is null or new.codigo = '' then new.codigo := set_codigo('VJ','calendario_visitas'); end if; return new; end $$;

-- Registra quien cambio que, cuando y con que valor anterior.
create or replace function public.registrar_historial()
returns trigger language plpgsql security definer set search_path = 'public' as $$
declare
  quien text;
  uid uuid := auth.uid();
  k text; va text; vd text; ident text;
begin
  select coalesce(nombre, email) into quien from usuarios where id = uid;
  quien := coalesce(quien, 'sistema');
  ident := coalesce((to_jsonb(coalesce(new, old)) ->> 'id'), '');

  if tg_op = 'INSERT' then
    insert into historial (tabla, fila_id, accion, usuario_id, usuario)
    values (tg_table_name, ident, 'creó', uid, quien);
    return new;
  elsif tg_op = 'DELETE' then
    insert into historial (tabla, fila_id, accion, usuario_id, usuario, antes)
    values (tg_table_name, ident, 'eliminó', uid, quien, left(to_jsonb(old)::text, 500));
    return old;
  else
    for k in select jsonb_object_keys(to_jsonb(new)) loop
      if k in ('updated_at','created_at') then continue; end if;
      va := to_jsonb(old) ->> k;
      vd := to_jsonb(new) ->> k;
      if coalesce(va,'') <> coalesce(vd,'') then
        insert into historial (tabla, fila_id, campo, antes, despues, accion, usuario_id, usuario)
        values (tg_table_name, ident, k, va, vd, 'editó', uid, quien);
      end if;
    end loop;
    return new;
  end if;
end $$;

-- Crea el perfil en public.usuarios cuando se da de alta en auth.users
create or replace function public.crear_perfil()
returns trigger language plpgsql security definer set search_path = 'public' as $$
begin
  insert into usuarios (id, email, nombre)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'nombre', split_part(new.email,'@',1)))
  on conflict (id) do nothing;
  return new;
end $$;

-- Impide que alguien se auto-promueva de rol o se reactive solo
create or replace function public.proteger_rol()
returns trigger language plpgsql security definer set search_path = 'public' as $$
begin
  if (new.rol is distinct from old.rol or new.activo is distinct from old.activo) and not es_admin() then
    raise exception 'Solo un administrador puede cambiar el rol o el acceso de un usuario';
  end if;
  return new;
end $$;

-- ---------------------------------------------------------------------
-- 5. Triggers
-- ---------------------------------------------------------------------

create trigger trg_codigo_portafolio before insert on public.portafolio
  for each row execute function public.set_codigo_portafolio();
create trigger trg_codigo_tarea before insert on public.tareas
  for each row execute function public.codigo_tarea();
create trigger trg_codigo_radar before insert on public.radar_paises
  for each row execute function public.codigo_radar();
create trigger trg_codigo_viaje before insert on public.calendario_visitas
  for each row execute function public.codigo_viaje();
create trigger trg_proteger_rol before update on public.usuarios
  for each row execute function public.proteger_rol();
create trigger trg_crear_perfil after insert on auth.users
  for each row execute function public.crear_perfil();

-- updated_at automatico
create trigger trg_touch_personas before update on public.personas
  for each row execute function public.tocar_updated_at();
create trigger trg_touch_actividades before update on public.actividades
  for each row execute function public.tocar_updated_at();
create trigger trg_touch_portafolio before update on public.portafolio
  for each row execute function public.tocar_updated_at();
create trigger trg_touch_tareas before update on public.tareas
  for each row execute function public.tocar_updated_at();
create trigger trg_touch_radar_paises before update on public.radar_paises
  for each row execute function public.tocar_updated_at();
create trigger trg_touch_contactos_paises before update on public.contactos_paises
  for each row execute function public.tocar_updated_at();
create trigger trg_touch_calendario_visitas before update on public.calendario_visitas
  for each row execute function public.tocar_updated_at();
create trigger trg_touch_config_listas before update on public.config_listas
  for each row execute function public.tocar_updated_at();

-- historial de cambios en todas las tablas de datos
create trigger trg_hist_personas after insert or update or delete on public.personas
  for each row execute function public.registrar_historial();
create trigger trg_hist_usuarios after insert or update or delete on public.usuarios
  for each row execute function public.registrar_historial();
create trigger trg_hist_actividades after insert or update or delete on public.actividades
  for each row execute function public.registrar_historial();
create trigger trg_hist_participaciones after insert or update or delete on public.participaciones
  for each row execute function public.registrar_historial();
create trigger trg_hist_capacidad_mensual after insert or update or delete on public.capacidad_mensual
  for each row execute function public.registrar_historial();
create trigger trg_hist_portafolio after insert or update or delete on public.portafolio
  for each row execute function public.registrar_historial();
create trigger trg_hist_tareas after insert or update or delete on public.tareas
  for each row execute function public.registrar_historial();
create trigger trg_hist_radar_paises after insert or update or delete on public.radar_paises
  for each row execute function public.registrar_historial();
create trigger trg_hist_contactos_paises after insert or update or delete on public.contactos_paises
  for each row execute function public.registrar_historial();
create trigger trg_hist_calendario_visitas after insert or update or delete on public.calendario_visitas
  for each row execute function public.registrar_historial();
create trigger trg_hist_config_listas after insert or update or delete on public.config_listas
  for each row execute function public.registrar_historial();
create trigger trg_hist_ajustes after insert or update or delete on public.ajustes
  for each row execute function public.registrar_historial();

-- ---------------------------------------------------------------------
-- 6. Row Level Security
--
-- Patron general en los modulos de datos:
--   select                -> cualquier usuario autenticado (incluye lector)
--   insert/update/delete  -> puede_editar() (admin o editor)
--
-- Excepciones:
--   config_listas, ajustes -> solo es_admin() escribe
--   historial              -> solo lectura; lo escriben los triggers
--   usuarios               -> cada uno su perfil; roles y bajas solo admin
--   mejora_continua        -> solo admin borra (preserva trazabilidad)
--   secretos               -> RLS activo SIN politicas: inaccesible desde
--                             el cliente. Es intencional; el linter lo
--                             reporta como INFO y se acepta a proposito.
-- ---------------------------------------------------------------------

alter table public.personas            enable row level security;
alter table public.usuarios            enable row level security;
alter table public.actividades         enable row level security;
alter table public.participaciones     enable row level security;
alter table public.capacidad_mensual   enable row level security;
alter table public.portafolio          enable row level security;
alter table public.tareas              enable row level security;
alter table public.radar_paises        enable row level security;
alter table public.contactos_paises    enable row level security;
alter table public.calendario_visitas  enable row level security;
alter table public.mejora_continua     enable row level security;
alter table public.historial           enable row level security;
alter table public.config_listas       enable row level security;
alter table public.ajustes             enable row level security;
alter table public.secretos            enable row level security;

-- Modulos de datos con el patron estandar
do $$
declare t text;
begin
  foreach t in array array[
    'personas','actividades','participaciones','capacidad_mensual',
    'portafolio','tareas','radar_paises','contactos_paises','calendario_visitas'
  ] loop
    execute format('create policy sel_%1$s on public.%1$I for select to authenticated using (true)', t);
    execute format('create policy ins_%1$s on public.%1$I for insert to authenticated with check (public.puede_editar())', t);
    execute format('create policy upd_%1$s on public.%1$I for update to authenticated using (public.puede_editar()) with check (public.puede_editar())', t);
    execute format('create policy del_%1$s on public.%1$I for delete to authenticated using (public.puede_editar())', t);
  end loop;
end $$;

-- Mejora continua: solo admin puede borrar, para no perder trazabilidad
create policy sel_mejora_continua on public.mejora_continua for select to authenticated using (true);
create policy ins_mejora_continua on public.mejora_continua for insert to authenticated with check (public.puede_editar());
create policy upd_mejora_continua on public.mejora_continua for update to authenticated using (public.puede_editar()) with check (public.puede_editar());
create policy del_mejora_continua on public.mejora_continua for delete to authenticated using (public.es_admin());

-- Historial: solo lectura desde el cliente
create policy historial_select on public.historial for select to authenticated using (true);

-- Configuracion: solo admin escribe
create policy sel_config_listas on public.config_listas for select to authenticated using (true);
create policy ins_config_listas on public.config_listas for insert to authenticated with check (public.es_admin());
create policy upd_config_listas on public.config_listas for update to authenticated using (public.es_admin()) with check (public.es_admin());
create policy del_config_listas on public.config_listas for delete to authenticated using (public.es_admin());

create policy ajustes_select on public.ajustes for select to authenticated using (true);
create policy ajustes_write  on public.ajustes for all    to authenticated using (public.es_admin()) with check (public.es_admin());

-- Usuarios: cada uno su perfil; roles y bajas solo admin
create policy usuarios_select on public.usuarios for select to authenticated using (true);
create policy usuarios_update_propio_o_admin on public.usuarios for update to authenticated
  using (id = auth.uid() or public.es_admin()) with check (id = auth.uid() or public.es_admin());
create policy usuarios_delete_admin on public.usuarios for delete to authenticated using (public.es_admin());
