-- =====================================================================
-- 0004 - Tabla notificaciones
--
-- La app la consulta desde la v1.2 (TABLAS.notificaciones) pero nunca
-- se creo. El codigo la envuelve en un try/catch con el comentario
-- "la tabla puede no existir todavia; no rompe el resto de la app", asi
-- que el panel de notificaciones siempre se vio vacio: no fallaba, no
-- tenia de donde leer. Es la causa real detras de la sensacion de que
-- "se habia perdido" en la v1.5.4.
--
-- El esquema replica exactamente lo que consulta el cliente:
--   .from("notificaciones").select("*")
--     .eq("destinatario_id", session.user.id).order("creado_en", ...)
--   .update({ leida: true }).eq("destinatario_id", ...).eq("leida", false)
-- y la UI lee: mensaje, tabla, registro_id, leida, creado_en.
--
-- VERIFICADO tras aplicar: se inserto un aviso para el usuario de smoke
-- test, se leyo con su sesion simulada, se confirmo que otro usuario NO
-- lo ve, y se elimino la fila de prueba.
-- =====================================================================

create table if not exists public.notificaciones (
  id bigint generated by default as identity primary key,
  destinatario_id uuid not null references public.usuarios(id) on delete cascade,
  mensaje text not null,
  tabla text,
  registro_id text,
  leida boolean not null default false,
  creado_en timestamptz not null default now()
);

comment on table public.notificaciones is
  'Avisos por usuario. La app los lee al iniciar sesion y los marca leidos al abrir el panel.';
comment on column public.notificaciones.tabla is
  'Modulo al que salta el aviso al tocarlo (portafolio, tareas, ...). Debe coincidir con las claves de TABLAS en el cliente.';
comment on column public.notificaciones.registro_id is
  'id de la fila destino, como texto. La app navega a ese registro al tocar el aviso.';

-- Consulta caliente: las de un usuario, mas nuevas primero
create index if not exists idx_notificaciones_destinatario
  on public.notificaciones(destinatario_id, creado_en desc);
-- Para el update masivo de "marcar todas como leidas"
create index if not exists idx_notificaciones_no_leidas
  on public.notificaciones(destinatario_id) where not leida;

alter table public.notificaciones enable row level security;

-- Cada quien ve SOLO las suyas (a diferencia del resto de los modulos,
-- donde el select es abierto a cualquier autenticado).
create policy sel_notificaciones on public.notificaciones
  for select to authenticated
  using (destinatario_id = auth.uid());

-- Solo puede marcar como leidas las propias; no puede reasignarlas.
create policy upd_notificaciones on public.notificaciones
  for update to authenticated
  using (destinatario_id = auth.uid())
  with check (destinatario_id = auth.uid());

-- Cualquier editor puede generar un aviso para otra persona
-- (ej. "te asignaron TAR-014"). Lector no.
create policy ins_notificaciones on public.notificaciones
  for insert to authenticated
  with check (puede_editar());

create policy del_notificaciones on public.notificaciones
  for delete to authenticated
  using (destinatario_id = auth.uid() or es_admin());
